package jp.rough_diamond.sample.esb.service.stub.sampleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Apr 06 19:40:26 JST 2010
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://service.esb.sample.rough_diamond.jp/", name = "SampleServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleServicePortType {

    @WebResult(name = "return", targetNamespace = "http://service.esb.sample.rough_diamond.jp/")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHello2Response")
    @WebMethod
    public java.lang.String sayHello2();

    @WebResult(name = "return", targetNamespace = "http://service.esb.sample.rough_diamond.jp/")
    @RequestWrapper(localName = "sayHello3", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHello3")
    @ResponseWrapper(localName = "sayHello3Response", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHello3Response")
    @WebMethod
    public java.lang.String sayHello3(
        @WebParam(name = "arg0", targetNamespace = "http://service.esb.sample.rough_diamond.jp/")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.esb.sample.rough_diamond.jp/", className = "jp.rough_diamond.sample.esb.service.stub.sampleservice.SayHelloResponse")
    @WebMethod
    public void sayHello();
}
