
package jp.rough_diamond.sample.esb.service.stub.sampleservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Apr 06 19:40:26 JST 2010
 * Generated source version: 2.1.2
 * 
 */

public final class SampleServicePortType_SampleServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.esb.sample.rough_diamond.jp/", "SampleService");

    private SampleServicePortType_SampleServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SampleService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SampleService ss = new SampleService(wsdlURL, SERVICE_NAME);
        SampleServicePortType port = ss.getSampleServicePort();  
        
        {
        System.out.println("Invoking sayHello2...");
        java.lang.String _sayHello2__return = port.sayHello2();
        System.out.println("sayHello2.result=" + _sayHello2__return);


        }
        {
        System.out.println("Invoking sayHello3...");
        java.lang.String _sayHello3_arg0 = "";
        java.lang.String _sayHello3__return = port.sayHello3(_sayHello3_arg0);
        System.out.println("sayHello3.result=" + _sayHello3__return);


        }
        {
        System.out.println("Invoking sayHello...");
        port.sayHello();


        }

        System.exit(0);
    }

}
