<?xml version="1.0" ?><wsdl:definitions name="MultiOperationService" targetNamespace="http://service.esb.sample.rough_diamond.jp/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.esb.sample.rough_diamond.jp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://service.esb.sample.rough_diamond.jp/" xmlns:tns="http://service.esb.sample.rough_diamond.jp/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="foo" type="tns:foo"></xsd:element>
    <xsd:complexType name="foo">
        <xsd:sequence></xsd:sequence>
    </xsd:complexType>
    <xsd:element name="fooResponse" type="tns:fooResponse"></xsd:element>
    <xsd:complexType name="fooResponse">
        <xsd:sequence></xsd:sequence>
    </xsd:complexType>
    <xsd:element name="bar" type="tns:bar"></xsd:element>
    <xsd:complexType name="bar">
        <xsd:sequence></xsd:sequence>
    </xsd:complexType>
    <xsd:element name="barResponse" type="tns:barResponse"></xsd:element>
    <xsd:complexType name="barResponse">
        <xsd:sequence></xsd:sequence>
    </xsd:complexType>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="barResponse">
    <wsdl:part element="tns:barResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="fooResponse">
    <wsdl:part element="tns:fooResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="bar">
    <wsdl:part element="tns:bar" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="foo">
    <wsdl:part element="tns:foo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="MultiOperationServicePortType">
    <wsdl:operation name="foo">
      <wsdl:input message="tns:foo" name="foo">
    </wsdl:input>
      <wsdl:output message="tns:fooResponse" name="fooResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="bar">
      <wsdl:input message="tns:bar" name="bar">
    </wsdl:input>
      <wsdl:output message="tns:barResponse" name="barResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MultiOperationServiceSoapBinding" type="tns:MultiOperationServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="foo">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="foo">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="fooResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="bar">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="bar">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="barResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MultiOperationService">
    <wsdl:port binding="tns:MultiOperationServiceSoapBinding" name="MultiOperationServicePort">
      <soap:address location="http://localhost:10080/services/MultiOperationService"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>